INSERT INTO physical_books (title, author, year, category, quantity) VALUES
-- ============================
--         CATEGORY: ART
-- ============================
('The Story of Art', 'E.H. Gombrich', 1950, 'art', 12),
('Ways of Seeing', 'John Berger', 1972, 'art', 17),
('The Art Book', 'Phaidon Editors', 1994, 'art', 9),
('Art: A World History', 'Elke Linda Buchholz', 2007, 'art', 19),
('Modern Art', 'Hans Werner Holzwarth', 2011, 'art', 15),
('The Lives of the Artists', 'Giorgio Vasari', 1550, 'art', 10),
('Concerning the Spiritual in Art', 'Wassily Kandinsky', 1911, 'art', 18),
('The Letters of Vincent van Gogh', 'Vincent van Gogh', 1914, 'art', 7),
('Michelangelo and the Pope’s Ceiling', 'Ross King', 2003, 'art', 14),
('Leonardo da Vinci', 'Walter Isaacson', 2017, 'art', 13),
('The Shock of the New', 'Robert Hughes', 1980, 'art', 11),
('What Are You Looking At?', 'Will Gompertz', 2012, 'art', 8),
('7 Days in the Art World', 'Sarah Thornton', 2008, 'art', 20),
('Art and Illusion', 'E.H. Gombrich', 1960, 'art', 6),
('Girl with a Pearl Earring', 'Tracy Chevalier', 1999, 'art', 16),
('The Anatomy of Colour', 'Patrick Baty', 2017, 'art', 17),
('Color and Light', 'James Gurney', 2010, 'art', 9),
('History of Beauty', 'Umberto Eco', 2004, 'art', 12),
('The Power of Art', 'Simon Schama', 2006, 'art', 14),
('Art in Theory 1900-2000', 'Charles Harrison', 1998, 'art', 18),
('The Art Spirit', 'Robert Henri', 1923, 'art', 10),
('Steal Like an Artist', 'Austin Kleon', 2012, 'art', 19),
('Daily Rituals: How Artists Work', 'Mason Currey', 2013, 'art', 8),
('Picasso: Creator and Destroyer', 'Ariadne Stassinopoulos', 1988, 'art', 13),
('The Painted Word', 'Tom Wolfe', 1975, 'art', 7),
('Art as Therapy', 'Alain de Botton', 2013, 'art', 11),
('The Letters of Paul Cézanne', 'Paul Cézanne', 2013, 'art', 5),
('Jean-Michel Basquiat', 'Phoebe Hoban', 1998, 'art', 12),
('Andy Warhol', 'Arthur C. Danto', 2009, 'art', 16),
('The Philosophy of Andy Warhol', 'Andy Warhol', 1975, 'art', 6),
('The Guggenheim: Frank Lloyd Wright', 'Bruce Brooks Pfeiffer', 2012, 'art', 15),
('The Art of Rivalry', 'Sebastian Smee', 2016, 'art', 9),
('Caravaggio: A Life Sacred and Profane', 'Andrew Graham-Dixon', 2011, 'art', 18),
('Matisse the Master', 'Hilary Spurling', 2005, 'art', 7),
('Rothko: A Biography', 'James E. B. Breslin', 1993, 'art', 13),
('The Art of Color', 'Johannes Itten', 1961, 'art', 17),
('The Letters of Frida Kahlo', 'Frida Kahlo', 1995, 'art', 10),
('The Art of Perspective', 'Phil Metzger', 2007, 'art', 19),
('The Art of Composition', 'Michel Jacobs', 1926, 'art', 8),
('The Louvre: All the Paintings', 'Vincent Pomarède', 2011, 'art', 14),
('Art and Visual Perception', 'Rudolf Arnheim', 1954, 'art', 12),
('The Principles of Painting', 'Roger de Piles', 1708, 'art', 6),
('Rembrandt: The Painter at Work', 'Ernst van de Wetering', 1997, 'art', 11),
('The Art of the Portrait', 'Norbert Schneider', 1999, 'art', 15),
('Anatomy for the Artist', 'Sarah Simblet', 2001, 'art', 16),
('The Art of Looking Sideways', 'Alan Fletcher', 2001, 'art', 20),
('The Art of Still Life', 'Todd M. Casey', 2020, 'art', 9),
('Botticelli', 'Frank Zöllner', 2015, 'art', 17),
('The Art of Painting', 'Roger de Piles', 1706, 'art', 7),

-- ===========================================================
--   CATEGORY: FICTION-ROMANCE-THRILLER (50 BOOKS)
-- ===========================================================

('The Great Gatsby', 'F. Scott Fitzgerald', 1925, 'fiction-romance-thriller', 18),
('Pride and Prejudice', 'Jane Austen', 1813, 'fiction-romance-thriller', 15),
('Gone Girl', 'Gillian Flynn', 2012, 'fiction-romance-thriller', 9),
('The Notebook', 'Nicholas Sparks', 1996, 'fiction-romance-thriller', 13),
('The Girl on the Train', 'Paula Hawkins', 2015, 'fiction-romance-thriller', 7),
('The Girl with the Dragon Tattoo', 'Stieg Larsson', 2005, 'fiction-romance-thriller', 19),
('Me Before You', 'Jojo Moyes', 2012, 'fiction-romance-thriller', 8),
('It Ends with Us', 'Colleen Hoover', 2016, 'fiction-romance-thriller', 11),
('The Da Vinci Code', 'Dan Brown', 2003, 'fiction-romance-thriller', 16),
('Angels & Demons', 'Dan Brown', 2000, 'fiction-romance-thriller', 17),
('Verity', 'Colleen Hoover', 2018, 'fiction-romance-thriller', 12),
('The Silent Patient', 'Alex Michaelides', 2019, 'fiction-romance-thriller', 14),
('Sharp Objects', 'Gillian Flynn', 2006, 'fiction-romance-thriller', 6),
('The Shining', 'Stephen King', 1977, 'fiction-romance-thriller', 15),
('It', 'Stephen King', 1986, 'fiction-romance-thriller', 13),
('Pet Sematary', 'Stephen King', 1983, 'fiction-romance-thriller', 11),
('Rebecca', 'Daphne du Maurier', 1938, 'fiction-romance-thriller', 10),
('The Time Traveler’s Wife', 'Audrey Niffenegger', 2003, 'fiction-romance-thriller', 9),
('The Fault in Our Stars', 'John Green', 2012, 'fiction-romance-thriller', 8),
('Twilight', 'Stephenie Meyer', 2005, 'fiction-romance-thriller', 20),
('New Moon', 'Stephenie Meyer', 2006, 'fiction-romance-thriller', 18),
('Eclipse', 'Stephenie Meyer', 2007, 'fiction-romance-thriller', 17),
('Breaking Dawn', 'Stephenie Meyer', 2008, 'fiction-romance-thriller', 16),
('The Hunger Games', 'Suzanne Collins', 2008, 'fiction-romance-thriller', 14),
('Catching Fire', 'Suzanne Collins', 2009, 'fiction-romance-thriller', 13),
('Mockingjay', 'Suzanne Collins', 2010, 'fiction-romance-thriller', 12),
('Divergent', 'Veronica Roth', 2011, 'fiction-romance-thriller', 11),
('Insurgent', 'Veronica Roth', 2012, 'fiction-romance-thriller', 10),
('Allegiant', 'Veronica Roth', 2013, 'fiction-romance-thriller', 9),
('The Girl in the Mirror', 'Rose Carlyle', 2020, 'fiction-romance-thriller', 7),
('The Woman in the Window', 'A.J. Finn', 2018, 'fiction-romance-thriller', 8),
('Before I Go to Sleep', 'S.J. Watson', 2011, 'fiction-romance-thriller', 6),
('The Couple Next Door', 'Shari Lapena', 2016, 'fiction-romance-thriller', 15),
('The Wife Between Us', 'Greer Hendricks', 2018, 'fiction-romance-thriller', 14),
('Big Little Lies', 'Liane Moriarty', 2014, 'fiction-romance-thriller', 12),
('Nine Perfect Strangers', 'Liane Moriarty', 2018, 'fiction-romance-thriller', 11),
('The Bourne Identity', 'Robert Ludlum', 1980, 'fiction-romance-thriller', 10),
('The Reversal', 'Michael Connelly', 2010, 'fiction-romance-thriller', 9),
('The Lincoln Lawyer', 'Michael Connelly', 2005, 'fiction-romance-thriller', 7),
('Dark Places', 'Gillian Flynn', 2009, 'fiction-romance-thriller', 8),
('The Shadow of the Wind', 'Carlos Ruiz Zafón', 2001, 'fiction-romance-thriller', 15),
('The Girl Who Played with Fire', 'Stieg Larsson', 2006, 'fiction-romance-thriller', 16),
('The Girl Who Kicked the Hornet’s Nest', 'Stieg Larsson', 2007, 'fiction-romance-thriller', 17),
('Inferno', 'Dan Brown', 2013, 'fiction-romance-thriller', 19),
('Origin', 'Dan Brown', 2017, 'fiction-romance-thriller', 14),
('The Chemist', 'Stephenie Meyer', 2016, 'fiction-romance-thriller', 9),

-- ===========================================================
--      CATEGORY: MEDICINE (50 BOOKS)
-- ===========================================================

('Gray''s Anatomy', 'Henry Gray', 1858, 'medicine', 16),
('Harrison''s Principles of Internal Medicine', 'J. Larry Jameson', 1950, 'medicine', 12),
('Robbins Basic Pathology', 'Vinay Kumar', 2017, 'medicine', 15),
('Medical Microbiology', 'Murray & Rosenthal', 2015, 'medicine', 7),
('Pharmacology', 'H.P. Rang', 2016, 'medicine', 11),
('Bates’ Guide to Physical Examination', 'Lynn Bickley', 2017, 'medicine', 9),
('Guyton and Hall Physiology', 'John E. Hall', 2016, 'medicine', 14),
('Basic and Clinical Pharmacology', 'Bertram Katzung', 2017, 'medicine', 8),
('The Immortal Life of Henrietta Lacks', 'Rebecca Skloot', 2010, 'medicine', 6),
('The Emperor of All Maladies', 'Siddhartha Mukherjee', 2010, 'medicine', 13),
('Nelson Textbook of Pediatrics', 'Kliegman', 2016, 'medicine', 12),
('Tintinalli''s Emergency Medicine', 'J. Stapczynski', 2015, 'medicine', 7),
('Principles of Neural Science', 'Kandel', 2012, 'medicine', 9),
('Atlas of Human Anatomy', 'Frank H. Netter', 2014, 'medicine', 5),
('Medical Genetics', 'Jorde', 2015, 'medicine', 11),
('Essentials of Cardiovascular Medicine', 'E.J. Topol', 2013, 'medicine', 8),
('The Gene: An Intimate History', 'Siddhartha Mukherjee', 2016, 'medicine', 10),
('The Man Who Mistook His Wife for a Hat', 'Oliver Sacks', 1985, 'medicine', 7),
('An Anthropologist on Mars', 'Oliver Sacks', 1995, 'medicine', 6),
('Awakenings', 'Oliver Sacks', 1973, 'medicine', 9),
('Being Mortal', 'Atul Gawande', 2014, 'medicine', 12),
('Complications', 'Atul Gawande', 2002, 'medicine', 8),
('Better', 'Atul Gawande', 2007, 'medicine', 13),
('How Doctors Think', 'Jerome Groopman', 2007, 'medicine', 15),
('The Checklist Manifesto', 'Atul Gawande', 2009, 'medicine', 11),

-- ===========================================================
--      CATEGORY: PHILOSOPHY (50 BOOKS)
-- ===========================================================

('Meditations', 'Marcus Aurelius', 180, 'philosophy', 14),
('The Republic', 'Plato', -380, 'philosophy', 9),
('Nicomachean Ethics', 'Aristotle', -340, 'philosophy', 7),
('Beyond Good and Evil', 'Friedrich Nietzsche', 1886, 'philosophy', 13),
('Thus Spoke Zarathustra', 'Friedrich Nietzsche', 1883, 'philosophy', 15),
('The Gay Science', 'Friedrich Nietzsche', 1882, 'philosophy', 6),
('Critique of Pure Reason', 'Immanuel Kant', 1781, 'philosophy', 10),
('Critique of Practical Reason', 'Immanuel Kant', 1788, 'philosophy', 11),
('Groundwork for the Metaphysics of Morals', 'Immanuel Kant', 1785, 'philosophy', 9),
('Being and Nothingness', 'Jean-Paul Sartre', 1943, 'philosophy', 12),
('Existentialism Is a Humanism', 'Jean-Paul Sartre', 1946, 'philosophy', 8),
('The Stranger', 'Albert Camus', 1942, 'philosophy', 16),
('The Myth of Sisyphus', 'Albert Camus', 1942, 'philosophy', 7),
('The Plague', 'Albert Camus', 1947, 'philosophy', 10),
('Phenomenology of Spirit', 'G.W.F. Hegel', 1807, 'philosophy', 14),
('Science of Logic', 'G.W.F. Hegel', 1812, 'philosophy', 5),
('The Social Contract', 'Jean-Jacques Rousseau', 1762, 'philosophy', 17),
('Discourse on Inequality', 'Jean-Jacques Rousseau', 1755, 'philosophy', 9),
('Leviathan', 'Thomas Hobbes', 1651, 'philosophy', 13),
('Two Treatises of Government', 'John Locke', 1689, 'philosophy', 11),
('An Enquiry Concerning Human Understanding', 'David Hume', 1748, 'philosophy', 12),
('A Treatise of Human Nature', 'David Hume', 1738, 'philosophy', 7),
('The Prince', 'Niccolò Machiavelli', 1532, 'philosophy', 18),
('Utopia', 'Thomas More', 1516, 'philosophy', 6),
('The Tao Te Ching', 'Laozi', -400, 'philosophy', 14),
('The Analects', 'Confucius', -475, 'philosophy', 13),
('The Bhagavad Gita', 'Vyasa', -200, 'philosophy', 12),
('The Art of War', 'Sun Tzu', -500, 'philosophy', 19),
('Meditations on First Philosophy', 'René Descartes', 1641, 'philosophy', 10),
('Discourse on Method', 'René Descartes', 1637, 'philosophy', 11),
('Ethics', 'Baruch Spinoza', 1677, 'philosophy', 5),
('The World as Will and Representation', 'Arthur Schopenhauer', 1818, 'philosophy', 9),
('The Problems of Philosophy', 'Bertrand Russell', 1912, 'philosophy', 7),
('A History of Western Philosophy', 'Bertrand Russell', 1945, 'philosophy', 15),
('Tractatus Logico-Philosophicus', 'Ludwig Wittgenstein', 1921, 'philosophy', 8),
('Philosophical Investigations', 'Ludwig Wittgenstein', 1953, 'philosophy', 13),
('On Liberty', 'John Stuart Mill', 1859, 'philosophy', 10),
('Utilitarianism', 'John Stuart Mill', 1863, 'philosophy', 11),
('The Ethics of Ambiguity', 'Simone de Beauvoir', 1947, 'philosophy', 6),
('The Second Sex', 'Simone de Beauvoir', 1949, 'philosophy', 9),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 1880, 'philosophy', 17),
('Crime and Punishment', 'Fyodor Dostoevsky', 1866, 'philosophy', 12),
('Notes from Underground', 'Fyodor Dostoevsky', 1864, 'philosophy', 8),
('The Trial', 'Franz Kafka', 1925, 'philosophy', 7),
('Man’s Search for Meaning', 'Viktor Frankl', 1946, 'philosophy', 14),
('The Rebel', 'Albert Camus', 1951, 'philosophy', 13),
('The Denial of Death', 'Ernest Becker', 1973, 'philosophy', 9),
('The Courage to Be', 'Paul Tillich', 1952, 'philosophy', 6),
('Sophie's World', 'Jostein Gaarder', 1991, 'philosophy', 11),

-- ===========================================================
--      CATEGORY: SCIENCE (50 BOOKS)
-- ===========================================================

('A Brief History of Time', 'Stephen Hawking', 1988, 'science', 17),
('The Universe in a Nutshell', 'Stephen Hawking', 2001, 'science', 15),
('The Grand Design', 'Stephen Hawking', 2010, 'science', 13),
('Cosmos', 'Carl Sagan', 1980, 'science', 18),
('Pale Blue Dot', 'Carl Sagan', 1994, 'science', 12),
('Astrophysics for People in a Hurry', 'Neil deGrasse Tyson', 2017, 'science', 16),
('Death by Black Hole', 'Neil deGrasse Tyson', 2007, 'science', 11),
('The Selfish Gene', 'Richard Dawkins', 1976, 'science', 14),
('The Blind Watchmaker', 'Richard Dawkins', 1986, 'science', 8),
('The Gene: An Intimate History', 'Siddhartha Mukherjee', 2016, 'science', 13),
('Silent Spring', 'Rachel Carson', 1962, 'science', 7),
('The Double Helix', 'James Watson', 1968, 'science', 10),
('Surely You’re Joking, Mr. Feynman!', 'Richard Feynman', 1985, 'science', 6),
('The Fabric of the Cosmos', 'Brian Greene', 2004, 'science', 18),
('The Elegant Universe', 'Brian Greene', 1999, 'science', 17),
('The Hidden Life of Trees', 'Peter Wohlleben', 2015, 'science', 11),
('The Sixth Extinction', 'Elizabeth Kolbert', 2014, 'science', 12),
('Why We Sleep', 'Matthew Walker', 2017, 'science', 15),
('The Body', 'Bill Bryson', 2019, 'science', 14),
('Sapiens', 'Yuval Noah Harari', 2011, 'science', 19),
('Homo Deus', 'Yuval Noah Harari', 2015, 'science', 18),
('21 Lessons for the 21st Century', 'Yuval Noah Harari', 2018, 'science', 9),
('The Immortal Life of Henrietta Lacks', 'Rebecca Skloot', 2010, 'science', 7),
('The Emperor of All Maladies', 'Siddhartha Mukherjee', 2010, 'science', 12),
('Gödel, Escher, Bach', 'Douglas Hofstadter', 1979, 'science', 6),
('Chaos', 'James Gleick', 1987, 'science', 13),
('The Order of Time', 'Carlo Rovelli', 2017, 'science', 9),
('Seven Brief Lessons on Physics', 'Carlo Rovelli', 2014, 'science', 14),
('The Demon-Haunted World', 'Carl Sagan', 1995, 'science', 10),
('The Varieties of Scientific Experience', 'Carl Sagan', 1985, 'science', 7),
('The Big Picture', 'Sean Carroll', 2016, 'science', 12),
('Something Deeply Hidden', 'Sean Carroll', 2019, 'science', 11),
('The Periodic Table', 'Primo Levi', 1975, 'science', 8),
('The Making of the Atomic Bomb', 'Richard Rhodes', 1987, 'science', 13),
('The Disappearing Spoon', 'Sam Kean', 2010, 'science', 17),
('The Weather Book', 'DK Publishing', 2020, 'science', 16),
('The Human Brain Book', 'Rita Carter', 2009, 'science', 9),
('Genome', 'Matt Ridley', 1999, 'science', 15),
('The Oxygen Advantage', 'Patrick McKeown', 2015, 'science', 10),
('Breath', 'James Nestor', 2020, 'science', 11),
('Life on Earth', 'David Attenborough', 1979, 'science', 14),
('The Magic of Reality', 'Richard Dawkins', 2011, 'science', 12),
('The Language of Life', 'Francis Collins', 2010, 'science', 8),
('The Dragons of Eden', 'Carl Sagan', 1977, 'science', 6),
('How to Create a Mind', 'Ray Kurzweil', 2012, 'science', 17),
('The Invention of Nature', 'Andrea Wulf', 2015, 'science', 7),
('The Hidden Half of Nature', 'David R. Montgomery', 2015, 'science', 13),
('The Genius of Birds', 'Jennifer Ackerman', 2016, 'science', 11),
('Behave', 'Robert Sapolsky', 2017, 'science', 15),

-- ===========================================================
--      CATEGORY: TECHNOLOGY (50 BOOKS)
-- ===========================================================

('Clean Code', 'Robert C. Martin', 2008, 'technology', 19),
('Clean Architecture', 'Robert C. Martin', 2017, 'technology', 15),
('The Pragmatic Programmer', 'Andrew Hunt & David Thomas', 1999, 'technology', 16),
('Introduction to Algorithms', 'Cormen, Leiserson, Rivest, Stein', 1990, 'technology', 9),
('Design Patterns', 'Gamma, Helm, Johnson, Vlissides', 1994, 'technology', 11),
('Code Complete', 'Steve McConnell', 1993, 'technology', 14),
('Refactoring', 'Martin Fowler', 1999, 'technology', 12),
('Working Effectively with Legacy Code', 'Michael Feathers', 2004, 'technology', 8),
('The Mythical Man-Month', 'Frederick Brooks', 1975, 'technology', 13),
('The Clean Coder', 'Robert C. Martin', 2011, 'technology', 6),
('Cracking the Coding Interview', 'Gayle Laakmann McDowell', 2008, 'technology', 17),
('Algorithms to Live By', 'Brian Christian & Tom Griffiths', 2016, 'technology', 10),
('The Phoenix Project', 'Gene Kim', 2013, 'technology', 9),
('The Unicorn Project', 'Gene Kim', 2019, 'technology', 12),
('Continuous Delivery', 'Jez Humble & David Farley', 2010, 'technology', 11),
('Site Reliability Engineering', 'Beyer et al.', 2016, 'technology', 8),
('The DevOps Handbook', 'Gene Kim et al.', 2016, 'technology', 15),
('Soft Skills', 'John Sonmez', 2014, 'technology', 16),
('Coders at Work', 'Peter Seibel', 2009, 'technology', 14),
('Working Backwards', 'Colin Bryar & Bill Carr', 2021, 'technology', 7),
('AI Superpowers', 'Kai-Fu Lee', 2018, 'technology', 10),
('Life 3.0', 'Max Tegmark', 2017, 'technology', 13),
('The Master Algorithm', 'Pedro Domingos', 2015, 'technology', 12),
('Hands-On Machine Learning', 'Aurélien Géron', 2017, 'technology', 9),
('Pattern Recognition and Machine Learning', 'Christopher Bishop', 2006, 'technology', 8),
('Deep Learning', 'Ian Goodfellow, Bengio & Courville', 2016, 'technology', 11),
('Artificial Intelligence: A Modern Approach', 'Russell & Norvig', 1995, 'technology', 6),
('Python Crash Course', 'Eric Matthes', 2015, 'technology', 14),
('Fluent Python', 'Luciano Ramalho', 2015, 'technology', 15),
('Eloquent JavaScript', 'Marijn Haverbeke', 2014, 'technology', 17),
('You Don’t Know JS', 'Kyle Simpson', 2015, 'technology', 12),
('JavaScript: The Good Parts', 'Douglas Crockford', 2008, 'technology', 9),
('Clean Code in Java', 'Václav Pech', 2019, 'technology', 10),
('Spring in Action', 'Craig Walls', 2018, 'technology', 13),
('Kubernetes in Action', 'Marko Lukša', 2017, 'technology', 7),
('Docker Deep Dive', 'Nigel Poulton', 2017, 'technology', 11),
('Cloud Native DevOps with Kubernetes', 'John Arundel', 2019, 'technology', 16),
('Learning SQL', 'Alan Beaulieu', 2005, 'technology', 8),
('SQL Antipatterns', 'Bill Karwin', 2010, 'technology', 12),
('Database Internals', 'Alex Petrov', 2019, 'technology', 14),
('Designing Data-Intensive Applications', 'Martin Kleppmann', 2017, 'technology', 18),
('The Art of Computer Programming Vol.1', 'Donald Knuth', 1968, 'technology', 6),
('The Art of Computer Programming Vol.2', 'Donald Knuth', 1969, 'technology', 7),
('The Art of Computer Programming Vol.3', 'Donald Knuth', 1973, 'technology', 8),
('Compilers: Principles, Techniques, and Tools', 'Aho, Lam, Sethi, Ullman', 1986, 'technology', 9),
('Operating System Concepts', 'Silberschatz, Galvin, Gagne', 1983, 'technology', 11),
('Computer Networks', 'Andrew S. Tanenbaum', 1981, 'technology', 13),
('Modern Operating Systems', 'Andrew S. Tanenbaum', 1992, 'technology', 15),
('The Linux Programming Interface', 'Michael Kerrisk', 2010, 'technology', 14),
('Understanding the Linux Kernel', 'Daniel Bovet', 2000, 'technology', 10);
